#!/bin/bash
set -e

sage -hg ci

sage -python setup.py sdist

echo "**********************************************************"
echo "* If this is an official FEMhub release, don't forget to *"
echo "* push the changes to the public GIT repository.   *"
echo "**********************************************************"
#./push
